### PR TITLE
Bugfix - Vector3::sign gives incorrect results due to i32 conversion

### LINKED ISSUE #864: `Vector3::sign` gives incorrect results due to i32 conversion
`godot_print!("{}", Vector3::new(0.2, -0.5, 0.0).sign());` prints `(0, 0, 0)`
in godot, `print(Vector3(0.2, -0.5, 0.0).sign())` prints `(1, -1, 0)`

This seems to be due to the `impl_vector_fns` macro which first converts vector elements to `i32` before getting their sign.

### PR DESCRIPTION
**Pull request by Yarwin**
fixes #864

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-865

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-865

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-865

File: godot-core/src/builtin/vectors/vector3.rs [hunk 1]
```diff
@@ -325,6 +325,12 @@ mod test {
         );
     }
 
+    #[test]
+    fn sign() {
+        let vector = Vector3::new(0.2, -0.5, 0.0);
+        assert_eq_approx!(vector.sign(), Vector3::new(1., -1., 0.));
```
Comment (Bromeon) [inline godot-core/src/builtin/vectors/vector3.rs:331]: This could be `assert_eq!`, no? Since the numbers can be precisely represented...

In other places too

File: godot-core/src/builtin/vectors/vector_macros.rs [hunk 2]
```diff
@@ -484,16 +484,17 @@ macro_rules! impl_vector_fns {
...
-                    match x.cmp(&0) {
-                        Ordering::Equal => 0,
-                        Ordering::Greater => 1,
-                        Ordering::Less => -1,
+                fn f(x: $Scalar) -> $Scalar {
+                    let r = x.partial_cmp(&(0 as $Scalar)).unwrap_or_else(|| panic!("Vector component {x} isn't signed!"));
+                    match r {
+                        Ordering::Equal => 0 as $Scalar,
+                        Ordering::Greater => 1 as $Scalar,
+                        Ordering::Less => -1 as $Scalar,
```
Comment (Bromeon) [inline godot-core/src/builtin/vectors/vector_macros.rs:492]: Maybe while at it, rename `x` to `c` for component. It's a bit misleading otherwise.

**Review by Bromeon — COMMENTED** [review]
Thanks a lot! 👍
