### PR TITLE
Fix doc comments not showing up if only some class members are documented

### LINKED ISSUE #810: Docs comments do not show up if only some of the class members/methods are documented
Newest master allows for documentation comments like `/// Hello` to be included in Godot's documentation view.

It has a bug that, if you have e.g. two methods exposed to the API, but *only one* of them is documented, then *neither* of the docs show up in the documentation view. You must document every public API for it to show up properly.

Repro project, see readme for images and step by step: https://github.com/RedMser/bug-repro-godot-rust-docs

### PR DESCRIPTION
**Pull request by Yarwin**
closes #810 

- Extend test case to feature some undocumented members of godot instances
- Change map&unwrap in docs.rs to filter_map (allow to document only subset of all the properties of a given class)
- ~~Add "docs" feature to plugin in constant_tests~~
- Generate documentation blocks for signals & constants on compile-time

### CODE REVIEW

**Comment by Yarwin** [comment]
Changing to draft; I just noticed in test/minimal reproduction that it doesn't cover the whole scope of the issue

image

**Comment by Yarwin** [comment]
fix'd – all the cases in minimal reproduction project has been covered.


image
image
image


It is worth nothing that [example](https://github.com/godot-rust/gdext/blob/master/godot/tests/docs.rs#L9) included in test docs causes documentation generation to fail silently (might be simply a message/length limit).

File: itest/rust/src/register_tests/constant_test.rs [hunk 1]
```diff
@@ -174,6 +174,8 @@ godot::sys::plugin_add!(
             register_methods_constants_fn: ::godot::private::ErasedRegisterFn {
                 raw: ::godot::private::callbacks::register_user_methods_constants::<HasOtherConstants>,
             },
+            #[cfg(all(since_api = "4.3", feature = "docs"))]
+            docs: None
```
Comment (bend-n) [inline itest/rust/src/register_tests/constant_test.rs:178]: this isnt going to compile, itest doesnt have a docs feature

Comment (bend-n) [reply itest/rust/src/register_tests/constant_test.rs:178]: well it doesnt change anything, because it can never be enabled

File: godot-macros/src/docs.rs [hunk 2]
```diff
@@ -46,17 +46,17 @@ pub fn make_inherent_impl_docs(
     ) -> Option<TokenStream> {
         let methods = functions
             .iter()
-            .map(make_method_docs)
-            .collect::<Option<String>>()?;
+            .filter_map(make_method_docs)
+            .collect::<String>();
```
Comment (bend-n) [inline godot-macros/src/docs.rs:50]: theres a new problem here-- i implemented the option stuff so as to save space when no documentation is provided for a function, but now you just have empty documentation. you need to check if the number of documented items is 0 and return none to save space here

File: itest/rust/src/register_tests/constant_test.rs (hunk 1 above)
Comment (Yarwin) [reply itest/rust/src/register_tests/constant_test.rs]: Makes sense, missed leftover – I removed it since itest probably won't be called with `godot-core/docs`/`godot/register-docs` anyway

File: godot-macros/src/docs.rs (hunk 2 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs:52]: Makes sense, fixed – method won't generate TokenStream in question if there is no need to do so

Comment (bend-n) [reply godot-macros/src/docs.rs:52]: its not when the `methods` are empty its when the methods have no documentation at all, i.e methods.iter().filter(has_docs).count() == 0

Comment (bend-n) [reply godot-macros/src/docs.rs:52]: you see when 
```rust
impl X {
   #[func] fn y(…) { }
}
```
we dont want to have a `<methods>` block

Comment (bend-n) [reply godot-macros/src/docs.rs:52]: you see when 
```rust
impl X {
   #[func] fn y(…) { }
}
```
we dont want to have a `<methods>` block

Comment (Yarwin) [reply godot-macros/src/docs.rs:52]: Sure thing – right now (on master) if no methods are present, the generated xml contains methods tag `<methods></methods>` with no children present, and same goes for signals and constants. I'll just check with test project if Godot has no issues with missing "methods" block in case if there is _some_ documentation

Comment (bend-n) [reply godot-macros/src/docs.rs:52]: I dont remember why i put the `Option`s in at all then...

But if its working fine right now, you should be able to make the function just return Some, and thus remove the function from existence as it was a IIFE moved out (makeshift `try`)

Comment (Yarwin) [reply godot-macros/src/docs.rs:53]: I took the more direct approach – I decided to keep all the declarations as an option and just handle it while generating docs.

**Comment by Yarwin** [comment]
From now on, empty tags are not generated in doc's xml if there isn't any documentation for blocks in question.
 
Another round of manual testing:
image

image

image

image

image

(frankly I could just generate given xml and call it a day, but I wanted to see if there isn't any weird, unexpected behavior or whatnot)

File: godot-macros/src/docs.rs [hunk 3]
```diff
@@ -70,22 +88,19 @@ pub fn make_inherent_impl_docs(
...
-            virtual_method_docs: ""
-        },
-    }
+        .filter_map(make_virtual_method_docs)
+        .collect::<String>();
+    virtual_methods
+        .is_empty()
+        .not()
+        .then(|| quote! { virtual_method_docs: #virtual_methods.into(), })
+        .unwrap_or_else(|| quote! { virtual_method_docs: None, })
```
Comment (bend-n) [inline godot-macros/src/docs.rs:103]: why did you obfuscate the match?
```suggestion
    match virtual_methods {
        "" => quote! { virtual_method_docs: None, },
        _ => quote! { virtual_method_docs: #virtual_methods.into(), }
    }
```

File: godot-macros/src/docs.rs [hunk 4]
```diff
@@ -39,24 +40,41 @@ pub fn make_inherent_impl_docs(
...
+            s.is_empty()
+                .not()
+                .then(|| quote!(Some(#s)))
+                .unwrap_or(quote! {None})
+        };
+        let (methods, signals, constants) = (
+            to_tokenstream(methods),
+            to_tokenstream(signals),
+            to_tokenstream(constants),
+        );
```
Comment (bend-n) [inline godot-macros/src/docs.rs:77]: Why are you doing this `s.is_empty().not().then().unwrap_or_else()` thing?
```suggestion
        let to_tokenstream = |s| match s {
           "" => quote! { Some(#s) },
           _ => quote! { None },
        };
        let (methods, signals, constants) = (
            to_tokenstream(methods),
            to_tokenstream(signals),
            to_tokenstream(constants),
        );
```

File: godot-core/src/docs.rs [hunk 5]
```diff
@@ -34,23 +34,33 @@ pub struct StructDocs {
...
+
+#[doc(hidden)]
+/// Generates documentation for given block if there is anything to document
+/// Returns empty string otherwise
+fn block_docstring_or_empty(block: Option<&'static str>, tag: &'static str) -> String {
+    match block {
+        Some(s) => format!("<{tag}>{s}</{tag}>"),
+        _ => "".to_string(),
+    }
 }
```
Comment (bend-n) [inline godot-core/src/docs.rs:57]: Is there any chance you could move the tags into the block at macro time instead?
```suggestion
fn block_docstring_or_empty(block: Option<&'static str>, tag: &'static str) -> String {
    block.map(|s| format!("<{tag}>{s}</{tag}>")).unwrap_or_default()
}
```

**Review by bend-n — CHANGES_REQUESTED** [review]

File: godot-core/src/docs.rs (hunk 5 above)
Comment (Yarwin) [reply godot-core/src/docs.rs]: It is an option for signals & constants – methods&virtual methods needs to be formatted during runtime :thinking:

File: godot-macros/src/docs.rs (hunk 4 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs]: fixed

File: godot-macros/src/docs.rs (hunk 3 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs]: fixed

File: godot-core/src/docs.rs [hunk 6]
```diff
@@ -34,23 +34,33 @@ pub struct StructDocs {
 /// ```
 #[derive(Clone, Copy, Debug, Default)]
 pub struct InherentImplDocs {
-    pub methods: &'static str,
-    pub signals: &'static str,
-    pub constants: &'static str,
+    pub methods: Option<&'static str>,
```
[the remark this answers is not in the document]
Comment (Yarwin) [reply godot-core/src/docs.rs:37]: I moved generation of signal & constant blocks to compile time, thus now InherentImplDocs holds 2x &'static str & one Option<&'static str>.

File: godot-core/src/docs.rs [hunk 7]
```diff
@@ -79,20 +79,24 @@ pub fn gather_xml_docs() -> impl Iterator<Item = String> {
...
+                signals_block,
+                constants_block,
             } = pieces.inherent;
 
             let virtual_methods = pieces.virtual_methods;
             let brief = description.split_once("[br]").map(|(x, _)| x).unwrap_or_default();
+            let methods_block: String = match methods.is_some() || virtual_methods.is_some() {
+                true => format!("<methods>{m}{vm}</methods>", m=methods.unwrap_or_default(), vm=virtual_methods.unwrap_or_default()),
+                _ => "".to_string()
+            };
```
Comment (Bromeon) [inline godot-core/src/docs.rs:91]: Use `if` instead of `match`

Also, `String::new()` instead of `"".to_string()`

File: godot-core/src/init/mod.rs [hunk 8]
```diff
@@ -144,7 +144,9 @@ unsafe fn gdext_on_level_init(level: InitLevel) {
         }
         InitLevel::Editor => {
             #[cfg(all(since_api = "4.3", feature = "docs"))]
-            crate::docs::register();
+            unsafe {
+                crate::docs::register();
+            }
```
Comment (Bromeon) [inline godot-core/src/init/mod.rs:149]: Why this change?

File: godot-macros/src/docs.rs [hunk 9]
```diff
@@ -39,52 +39,62 @@ pub fn make_inherent_impl_docs(
...
     fn pieces(
         functions: &[FuncDefinition],
         signals: &[SignalDefinition],
         constants: &[ConstDefinition],
-    ) -> Option<TokenStream> {
+    ) -> TokenStream {
+        let to_tagged = |s: String, tag: &str| match s.is_empty() {
+            true => s,
+            _ => format!("<{tag}>{s}</{tag}>"),
+        };
```
Comment (Bromeon) [inline godot-macros/src/docs.rs:51]: `if`

File: godot-macros/src/docs.rs [hunk 10]
```diff
@@ -39,52 +39,62 @@ pub fn make_inherent_impl_docs(
...
+            signals
+                .iter()
+                .filter_map(make_signal_docs)
+                .collect::<String>(),
+            "signals",
+        );
+        let constants_block = to_tagged(
+            constants
+                .iter()
+                .map(|ConstDefinition { raw_constant: x }| x)
```
Comment (Bromeon) [inline godot-macros/src/docs.rs:62]:
```suggestion
                .map(|ConstDefinition { raw_constant }| raw_constant)
```

File: godot-macros/src/docs.rs [hunk 11]
```diff
@@ -39,52 +39,62 @@ pub fn make_inherent_impl_docs(
...
-            .map(|ConstDefinition { raw_constant: x }| x)
-            .map(make_constant_docs)
-            .collect::<Option<String>>()?;
-        let field_definition = quote! {
+            .filter_map(make_method_docs)
+            .collect::<String>();
+        let methods = match methods.is_empty() {
+            true => quote! { None },
+            _ => quote! {#methods.into()},
+        };
```
Comment (Bromeon) [inline godot-macros/src/docs.rs:74]: `if`

File: godot-macros/src/docs.rs [hunk 12]
```diff
@@ -39,52 +39,62 @@ pub fn make_inherent_impl_docs(
...
-    {
-        Some(vmethods) => quote! {
-            virtual_method_docs: #vmethods,
-        },
-        None => quote! {
-            virtual_method_docs: ""
-        },
+        .filter_map(make_virtual_method_docs)
+        .collect::<String>();
+    match virtual_methods.is_empty() {
```
Comment (Bromeon) [inline godot-macros/src/docs.rs:95]: Please empty line before, to separate complex multi-line statements.
Again, `if`.

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-815

**Review by Bromeon — COMMENTED** [review]
Thank you!

There are some Clippy issues.

**Comment by Bromeon** [comment]
Clippy issues are independent of this PR, I'll fix them.

File: godot-core/src/init/mod.rs (hunk 8 above)
Comment (Yarwin) [reply godot-core/src/init/mod.rs:149]: I can't compile godot-core without declaring this function call as unsafe :shrug:. 

```cmd
irwin@toster:~/(…)/missing_docs/bug-repro-godot-rust-docs-master/docstest$ cargo build
   Compiling godot-macros v0.1.3 (/home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-macros)
   Compiling godot-core v0.1.3 (/home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core)
error: call to unsafe function `docs::register` is unsafe and requires unsafe block (error E0133)
   --> /home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core/src/init/mod.rs:147:13
    |
147 |             crate::docs::register();
    |             ^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: for more information, see issue #71668 <https://github.com/rust-lang/rust/issues/71668>
    = note: consult the function's documentation for information on how to avoid undefined behavior
note: an unsafe function restricts its caller, but its body is safe by default
   --> /home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core/src/init/mod.rs:132:1
    |
132 | unsafe fn gdext_on_level_init(level: InitLevel) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: the lint level is defined here
   --> /home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core/src/init/mod.rs:131:8
    |
131 | #[deny(unsafe_op_in_unsafe_fn)]
    |        ^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `godot-core` (lib) due to 1 previous error

```

Comment (Yarwin) [reply godot-core/src/init/mod.rs:149]: call to `crate::docs::register()` is unsafe if experimental-threads feature is enabled. 

Should I create two variants of `crate::docs::register()` that depends on set features?

File: godot-macros/src/docs.rs (hunk 3 above)
Comment (bend-n) [reply godot-macros/src/docs.rs]: why are you applying my suggestion weirdly? you seem to really want to use `is_empty`

File: godot-core/src/init/mod.rs (hunk 8 above)
Comment (Yarwin) [reply godot-core/src/init/mod.rs:149]: Call to `crate::docs::register();` is unsafe and I can't compile test project without explicitly marking this call as unsafe :thinking: .

```rust
irwin@toster:~/apps/godot/opensource-contr/missing_docs/bug-repro-godot-rust-docs-master/docstest$ cargo build
   Compiling godot-core v0.1.3 (/home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core)
error: call to unsafe function `docs::register` is unsafe and requires unsafe block (error E0133)
   --> /home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core/src/init/mod.rs:147:17
    |
147 |                 crate::docs::register();
    |                 ^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: for more information, see issue #71668 <https://github.com/rust-lang/rust/issues/71668>
    = note: consult the function's documentation for information on how to avoid undefined behavior
note: an unsafe function restricts its caller, but its body is safe by default
   --> /home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core/src/init/mod.rs:132:1
    |
132 | unsafe fn gdext_on_level_init(level: InitLevel) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: the lint level is defined here
   --> /home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core/src/init/mod.rs:131:8
    |
131 | #[deny(unsafe_op_in_unsafe_fn)]
    |        ^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `godot-core` (lib) due to 1 previous error
```

```rust
/missing_docs/gdext/godot$ cargo test --features register-docs,api-custom,godot-core/docs,godot-core/api-custom -- --nocapture
   Compiling godot-macros v0.1.3 (/home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-macros)
   Compiling godot-core v0.1.3 (/home/irwin/apps/godot/opensource-contr/missing_docs/gdext/godot-core)
error: call to unsafe function `docs::register` is unsafe and requires unsafe block (error E0133)
   --> godot-core/src/init/mod.rs:147:13
    |
147 |             crate::docs::register();
    |             ^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
    |
    = note: for more information, see issue #71668 <https://github.com/rust-lang/rust/issues/71668>
    = note: consult the function's documentation for information on how to avoid undefined behavior
note: an unsafe function restricts its caller, but its body is safe by default
   --> godot-core/src/init/mod.rs:132:1
    |
132 | unsafe fn gdext_on_level_init(level: InitLevel) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: the lint level is defined here
   --> godot-core/src/init/mod.rs:131:8
    |
131 | #[deny(unsafe_op_in_unsafe_fn)]
    |        ^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `godot-core` (lib) due to 1 previous error
```

Comment (bend-n) [reply godot-core/src/init/mod.rs:149]: Are you using rust 2024?

Comment (bend-n) [reply godot-core/src/init/mod.rs:149]: Somebody must have put that deny in there and forgotten to check the #[cfg]d out things i suppose...

File: godot-macros/src/docs.rs (hunk 11 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs]: fixed

File: godot-macros/src/docs.rs (hunk 12 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs]: if'ed and multi-lined

File: godot-macros/src/docs.rs (hunk 10 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs]: fixed

File: godot-macros/src/docs.rs (hunk 9 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs]: fixed

File: godot-core/src/docs.rs (hunk 7 above)
Comment (Yarwin) [reply godot-core/src/docs.rs]: done

File: godot-core/src/init/mod.rs (hunk 8 above)
Comment (Yarwin) [reply godot-core/src/init/mod.rs:149]: @bend-n it seems so 
image

Comment (Bromeon) [reply godot-core/src/init/mod.rs:149]: Good remark, I'll make sure this feature is enabled in at least one CI run.

For now, you can add the `unsafe` block and prepend it with a safety assertion line:
```rs
// SAFETY: binding has been initialized at this point.
```

File: godot-macros/src/docs.rs (hunk 9 above)
Comment (Bromeon) [reply godot-macros/src/docs.rs]: Not fixed in the diff. Did you forget to push?

**Review by Bromeon — COMMENTED** [review]
Thanks! Could you 
- include the missing commits with the amendments
- rebase onto master 
- squash the commits, in line with [this](https://github.com/godot-rust/gdext/blob/master/Contributing.md#one-commit-per-logical-change)?

File: godot-core/src/init/mod.rs (hunk 8 above)
Comment (Bromeon) [reply godot-core/src/init/mod.rs:149]: Done: https://github.com/godot-rust/gdext/pull/819
I can later rebase this PR onto `master`, to make sure the CI passes.

**Comment by Bromeon** [comment]
Fixed the formatting and the commit message. Please don't refer to issues via link or # in commit message, because this creates [a ton of spam](https://github.com/godot-rust/gdext/issues/810) on the tickets as you iterate:
image


There are still a few more things to do but we're getting closer, will add another comment :slightly_smiling_face:

**Review by Bromeon — COMMENTED** [review]
Thanks! Looks mostly good, but there's still [one CI problem](https://github.com/godot-rust/gdext/actions/runs/10124293064/job/27998864849?pr=815#step:3:346) to be addressed.

To me it's still not quite clear why the handling of methods, signals and constant is different: some declared as `Option<&'static str>`, some as `&'static str`; some evaluated XMLtags before others.

You mentioned this in multiple comments, but I didn't see _why_ this is done. What's the rationale? Can we not do the processing for different symbols at the same stage?

**Comment by Yarwin** [comment]
@Bromeon initially I was generating all the required xml during initialization in `godot-core/src/docs.rs:gather_xml_docs`. 
I was asked by @bend-n <https://github.com/godot-rust/gdext/pull/815#discussion_r1693941646> to do so at compile time – but I don't know how to deal with two separate method blocks (virtual ones, coming from inherent impl (`#[godot_api] impl MyType), and trait ones (`#[godot_api] impl IGodot for MyType)) that are being processed independently :thinking:.

I can revert to generating all the docs blocks on runtime/during plugin registration in `godot-core/src/docs.rs:gather_xml_docs`.

**Comment by bend-n** [comment]
im talking about the tags part: i.e, instead of storing `Some("<method>this is documentation</method>...")` you can store `Some("<methods><method></method></methods>")`, but its not very important

**Comment by Yarwin** [comment]
I can revert to initial solution then

**Comment by Bromeon** [comment]
> I don't know[1] how to deal with two separate method blocks (one coming from inherent impl (`#[godot_api] impl MyType`) and another coming from IGodot trait impl (`#[godot_api] impl IGodot for MyType`)) that are being processed independently 🤔 – thus I settled on weird solution, splitting it in half.

Ah, that makes sense. I would actually even argue not too much should be processed at compile time, because compile times in Rust are _already_ slow. I'm not sure if one would feel much impact during load time (and it's not like released games need this feature, it's mostly during development and for plugins).

So I think you can leave this for now -- please just add a comment above the plugin declarations that explains this design rationale. :+1:

File: godot-core/src/docs.rs [hunk 13]
```diff
@@ -7,6 +7,7 @@
 use crate::registry::plugin::PluginItem;
 use std::collections::HashMap;
 
+#[doc(hidden)]
```
Comment (Bromeon) [inline godot-core/src/docs.rs:10]: Is this necessary? If I check [latest API docs](https://godot-rust.github.io/docs/gdext/master/godot/?search=StructDocs), I don't find the symbol.

If it's indeed necessary, attributes should come after the `///` comment block.

File: godot-core/src/docs.rs [hunk 14]
```diff
@@ -23,40 +24,57 @@ pub struct StructDocs {
...
 #[doc(hidden)]
 /// This function scours the registered plugins to find their documentation pieces,
 /// and strings them together.
 ///
-/// It returns an iterator over XML documents.
+/// Returns an iterator over XML documents.
+///
+/// Documentation for signals and constants is being processed on compile time
+/// and can take a form of an already formatted xml `<block><doc></doc>…</block>` or an
+/// empty string if no such attribute has been documented.
```
Comment (Bromeon) [inline godot-core/src/docs.rs:66]:
```suggestion
/// Documentation for signals and constants is being processed at compile time
/// and can take the form of an already formatted XML `<block><doc></doc>…</block>`, or an
/// empty string if no such attribute has been documented.
```

File: godot-core/src/docs.rs [hunk 15]
```diff
@@ -23,40 +24,57 @@ pub struct StructDocs {
...
+///
+/// Since documentation for methods comes from two different sources
+/// – Inherent Implementation (`methods`) and IGodotType trait implementation (`virtual_method_docs`) –
+/// it is undesirable to merge these on compile time, and they are being kept as an optional strings of not-yet-parented xml tags
+/// (or nothing if no method has been documented).
```
Comment (Bromeon) [inline godot-core/src/docs.rs:71]:
```suggestion
/// Since documentation for methods comes from two different sources
/// -– inherent Implementation (`methods`) and I* trait implementation (`virtual_method_docs`) –-
/// it is undesirable to merge them at compile time. Instead, they are kept as optional strings of not-yet-parented XML tags
/// (or nothing if no method has been documented).
```

File: godot-core/src/docs.rs [hunk 16]
```diff
@@ -79,20 +97,23 @@ pub fn gather_xml_docs() -> impl Iterator<Item = String> {
...
+                signals_block,
+                constants_block,
             } = pieces.inherent;
 
             let virtual_methods = pieces.virtual_methods;
-            let brief = description.split_once("[br]").map(|(x, _)| x).unwrap_or_default();
+            let methods_block: String = if methods.is_some() || virtual_methods.is_some() { format!("<methods>{m}{vm}</methods>", m=methods.unwrap_or_default(), vm=virtual_methods.unwrap_or_default()) } else { String::new()};
+
+        let brief = description.split_once("[br]").map(|(x, _)| x).unwrap_or_default();
+
```
Comment (Bromeon) [inline godot-core/src/docs.rs:108]: I fixed the formatting of this in my commit, but you reverted it now. Please restore.

File: godot-macros/src/docs.rs [hunk 17]
```diff
@@ -39,52 +39,72 @@ pub fn make_inherent_impl_docs(
...
-            .map(make_constant_docs)
-            .collect::<Option<String>>()?;
-        let field_definition = quote! {
+            .filter_map(make_method_docs)
+            .collect::<String>();
+
+        let methods = if methods.is_empty() {
+            quote! { None }
+        } else {
+            quote! {#methods.into()}
```
Comment (Bromeon) [inline godot-macros/src/docs.rs:80]:
```suggestion
            quote! { #methods.into() }
```
Also, what does the `.into()` do here? Is it possible to make the conversion more explicit? Since this is non-local generated code, things can be quite hard to understand otherwise.

File: godot/tests/docs.rs [hunk 18]
```diff
@@ -75,57 +76,92 @@ use godot::prelude::*;
...
     }
+
+    #[signal]
+    fn undocumented_signal(p: Vector3, w: f64);
+
+    #[signal]
+    /// some user signal
+    ///
+    /// some multiline doc
+    fn documented_signal(p: Vector3, w: f64);
```
Comment (Bromeon) [inline godot/tests/docs.rs:153]: Also here, would be good to have Rustdoc before attributes.

We don't need to fix it everywhere (it may be good to have one other case just for testing), but for lines that are added or changed already.

File: godot-macros/src/docs.rs (hunk 17 above)
Comment (bend-n) [reply godot-macros/src/docs.rs:80]: The into was for `T => Some(T)` but it isnt necessary anymore and I put it into a review comment but it didnt actually get changed

Comment (Bromeon) [reply godot-macros/src/docs.rs:80]: Let's write `Some(...)` then. 10 times clearer.

That's one thing I truly hate about `From`, it sometimes encourages obfuscation with zero benefits.

File: godot-core/src/docs.rs (hunk 15 above)
Comment (Yarwin) [reply godot-core/src/docs.rs:71]: Why a  `-– … –-` if I can ask?

File: godot-macros/src/docs.rs (hunk 17 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs:80]: I'll change it to `Some(…)`, I aimed to keep it consistent with earlier version

File: godot-macros/src/docs.rs [hunk 19]
```diff
@@ -39,52 +39,72 @@ pub fn make_inherent_impl_docs(
...
-        None => quote! {
-            virtual_method_docs: ""
-        },
+        .filter_map(make_virtual_method_docs)
+        .collect::<String>();
+
+    if virtual_methods.is_empty() {
+        quote! { virtual_method_docs: None, }
+    } else {
+        quote! { virtual_method_docs: #virtual_methods.into(), }
```
Comment (Bromeon) [inline godot-macros/src/docs.rs:107]:
```suggestion
        quote! { virtual_method_docs: Some(#virtual_methods), }
```

File: godot-core/src/docs.rs [hunk 20]
```diff
@@ -79,20 +95,33 @@ pub fn gather_xml_docs() -> impl Iterator<Item = String> {
...
+                constants_block,
             } = pieces.inherent;
 
             let virtual_methods = pieces.virtual_methods;
-            let brief = description.split_once("[br]").map(|(x, _)| x).unwrap_or_default();
+            let methods_block = if methods.is_some() || virtual_methods.is_some() {
+                format!(
+                    "<methods>{m}{vm}</methods>",
+                    m=methods.unwrap_or_default(),
+                    vm=virtual_methods.unwrap_or_default())
```
Comment (Bromeon) [inline godot-core/src/docs.rs:107]:
```suggestion
                    "<methods>{m}{vm}</methods>",
                    m = methods.unwrap_or_default(),
                    vm = virtual_methods.unwrap_or_default())
```
I missed this, sorry.

File: godot-core/src/docs.rs [hunk 21]
```diff
@@ -23,40 +23,56 @@ pub struct StructDocs {
     pub members: &'static str,
 }
 
-/// Created for documentation on
+/// Keeps documentation for Inherent Implementation such as:
```
Comment (Bromeon) [inline godot-core/src/docs.rs:26]:
```suggestion
/// Keeps documentation for inherent `impl` blocks, such as:
```

File: godot-core/src/docs.rs [hunk 22]
```diff
@@ -23,40 +23,56 @@ pub struct StructDocs {
...
 ///     #[func]
 ///     /// This function panics!
 ///     fn panic() -> f32 { panic!() }
+///     #[signal]
+///     /// this signal signals
+///     fn documented_signal(p: Vector3, w: f64);
+///     #[constant]
+///     /// this constant consts
+///     const CON: i64 = 42;
+///
```
Comment (Bromeon) [inline godot-core/src/docs.rs:39]:
```suggestion
///     #[signal]
///     /// this signal signals
///     fn documented_signal(p: Vector3, w: f64);
///
///     #[constant]
///     /// this constant consts
///     const CON: i64 = 42;
```
(I just moved the empty line from the end to between them, no clue why the diff is so weird)

File: godot-core/src/docs.rs [hunk 23]
```diff
@@ -23,40 +23,56 @@ pub struct StructDocs {
...
+/// Documentation for signals and constants is being processed at compile time
+/// and can take the form of an already formatted XML `<block><doc></doc>…</block>`, or an
+/// empty string if no such attribute has been documented.
+///
+/// Since documentation for methods comes from two different sources
+/// -– inherent Implementation (`methods`) and I* trait implementation (`virtual_method_docs`) –-
+/// it is undesirable to merge them at compile time. Instead, they are being kept as an optional
+/// strings of not-yet-parented XML tags
+/// (or nothing if no method has been documented).
```
Comment (Bromeon) [inline godot-core/src/docs.rs:69]:
```suggestion
/// Since documentation for methods comes from two different sources
/// -- inherent implementations (`methods`) and `I*` trait implementations (`virtual_method_docs`) --
/// it is undesirable to merge them at compile time. Instead, they are being kept as an optional
/// strings of not-yet-parented XML tags (or nothing if no method has been documented).
```

**Review by Bromeon — COMMENTED** [review]
Thanks for the patience, only few things left -- but you should be able to apply them directly :slightly_smiling_face:

**Comment by Bromeon** [comment]
Thanks a lot!

File: godot-macros/src/docs.rs [hunk 24]
```diff
@@ -39,52 +39,72 @@ pub fn make_inherent_impl_docs(
...
-            virtual_method_docs: ""
-        },
+        .filter_map(make_virtual_method_docs)
+        .collect::<String>();
+
+    if virtual_methods.is_empty() {
+        quote! { virtual_method_docs: None, }
+    } else {
+        quote! { virtual_method_docs: Some(#virtual_methods), }
     }
```
Comment (bend-n) [inline godot-macros/src/docs.rs:108]: the way this is used seems a bit silly, as its just unwrap_or_default'd later:
```rust
            let methods_block = if methods.is_some() || virtual_methods.is_some() {
                format!(
                    "<methods>{m}{vm}</methods>",
                    m = methods.unwrap_or_default(),
                    vm = virtual_methods.unwrap_or_default())
            } else {
                String::new()
            };
```
can that be changed to just
```rust
(virtual_methods.len() + methods.len() > 0)
   .then(|| format!("<methods>{methods}{virtual_methods}</methods>"))
   .unwrap_or_default()
```
and do this here: (and in the make method docs function)
```suggestion
    quote! { virtual_method_docs: #virtual_methods }
```
?

**Review by bend-n — CHANGES_REQUESTED** [review]
Some of these options seem slightly pointless, as what you seem to be doing is
```rust
let thing = x.is_empty().then(|| String::default()).unwrap_or(x);

// later
if thing.is_some() && … {
	thing.unwrap_or_default()
}
```

**Comment by Bromeon** [comment]
Good that CI failed then 😁 there's an unrelated `cargo-deny` failure, no clue why exactly now...

File: godot-macros/src/docs.rs (hunk 24 above)
Comment (Yarwin) [reply godot-macros/src/docs.rs:108]: thanks a lot! It actually works fine and looks like the cleanest and the least messy solution
