### PR TITLE
Map "Self" to class name in functions.

### LINKED ISSUE #578: `Gd<Self>` return type causes type error when fn annotated with `#[func]`
Sorry if dupe, mentioned this on the discord and @PgBiel said it was discussed before but might not have an issue open. From a quick search, I couldn't seem to find a thread for it.

The specific error:
```
can't use generic parameters from outer item
    use of generic parameter from outer item
```

Reproduce:

```rs
#[godot_api]
impl SomeCustomClass {
    // Uncomment the line below for a sussy wussy type error :D
    // #[func]
    pub fn do_some_stuff() -> Gd<Self> {
        todo!()
    }
}
```

### PR DESCRIPTION
**Pull request by vortexofdoom**
Alternative, probably better implementation of #590. Keeps the utils clean, and uses the cloning of the tokens that's happening anyway to make the swap instead. I did address the lint on `&Vec<_>` vs `&[_]` that Clippy caught in utils the first time around, though.

This doesn't affect Signals as far as I can tell at the moment, since I don't think those generate nested functions.

Fixes #578

### CODE REVIEW

**Review by Bromeon — COMMENTED** [review]
Thanks a lot, this is a great contribution! 🙂 

Could you write a test for the simple and a nested case?
1. In `object_test.rs`, there is already `ObjectTest::return_object()`, whose return type you could just change from `Gd<ObjectTest>` to `Gd<Self>`.

2. Since you support nested expressions, it would be good to test that, too. To get to the limits, you could add a new method that returns something like:
    ```rs
    Array<Gd<<Self as GodotClass>::Base>>
    ``` 
    and then return the same object, but upcast and wrapped in a 1-element array.

What do you think?

---

Also in general, feel free to reuse the same pull request for iterations of the implementation; you can just force-push to the existing one. It makes organization a bit easier (e.g. if someone later looks for this, there's only one candidate).

File: godot-macros/src/class/data_models/func.rs [hunk 1]
```diff
@@ -252,18 +256,47 @@ fn make_forwarding_closure(
...
+        // Pass all other tokens through unchanged.
+        tt => tt.clone(),
+    }
+}
+
+pub(crate) fn get_signature_info(
+    class_name: &Ident,
+    signature: &venial::Function,
+    has_gd_self: bool,
+) -> SignatureInfo {
```
[the remark this answers is not in the document]
Comment (vortexofdoom) [reply godot-macros/src/class/data_models/func.rs:283]: It looks like this works. I suspect that the `quote!` macro may already clone referenced tokens under the hood if giving owned streams back, and we were definitely cloning the parameter types before, so I changed as little as possible to start, but will do.

File: godot-macros/src/class/data_models/func.rs [hunk 2]
```diff
@@ -292,7 +325,14 @@ pub(crate) fn get_signature_info(signature: &venial::Function, has_gd_self: bool
...
                 };
-                let ty = arg.ty.clone();
+                let ty = venial::TyExpr {
+                    tokens: arg
+                        .ty
+                        .tokens
+                        .iter()
+                        .map(|tt| map_self_to_class_name(tt, class_name))
+                        .collect(),
+                };
```
[the remark this answers is not in the document]
Comment (vortexofdoom) [reply godot-macros/src/class/data_models/func.rs:335]: I might be able to pull out all 3 usages of the basic pattern into a function that takes an `impl IntoIterator` and returns a `FromIterator`? I'll mess around with that later today, otherwise the `TyExpr` specific one should be pretty easy.

[the remark this answers is not in the document]
Comment (Bromeon) [reply godot-macros/src/class/data_models/func.rs:335]: Using iterators sounds good, too. There's also the [`quote::ToTokens`](https://docs.rs/quote/latest/quote/trait.ToTokens.html#method.to_token_stream) trait with `into_token_stream()`, but it seems not implemented for `Vec<TokenTree>`, so not sure if it would be directly applicable.

File: godot-macros/src/class/data_models/func.rs [hunk 3]
```diff
@@ -81,7 +83,10 @@ pub fn make_method_registration(
     } else {
         method_name.to_string()
     };
-    let param_ident_strs = param_idents.iter().map(|ident| ident.to_string());
+    let param_ident_strs = signature_info
+        .param_idents
+        .into_iter()
+        .map(|ident| (ident).to_string());
```
Comment (Bromeon) [inline godot-macros/src/class/data_models/func.rs:89]: Why did you add parentheses here? 😀

File: godot-macros/src/class/data_models/func.rs [hunk 4]
```diff
@@ -252,22 +257,49 @@ fn make_forwarding_closure(
...
+            // Recurse into groups and make sure ALL instances are changed.
+            TokenTree::Group(group) => TokenTree::Group(Group::new(
+                group.delimiter(),
+                map_self_to_class_name(group.stream(), class_name),
+            )),
+            // Pass all other tokens through unchanged.
+            tt => tt,
+        })
+        .collect()
+}
```
Comment (vortexofdoom) [inline godot-macros/src/class/data_models/func.rs:280]: I just pulled the map into a closure, should have thought of this yesterday but we got there.

File: godot-macros/src/class/data_models/func.rs [hunk 5]
```diff
@@ -59,18 +59,20 @@ pub fn make_method_registration(
...
+    let signature_info = into_signature_info(
+        class_name,
+        func_definition.func,
+        func_definition.has_gd_self,
+    );
     let sig_tuple =
         util::make_signature_tuple_type(&signature_info.ret_type, &signature_info.param_types);
 
-    let method_name = &signature_info.method_name;
-    let param_idents = &signature_info.param_idents;
```
Comment (vortexofdoom) [inline godot-macros/src/class/data_models/func.rs:67]: didn't really need a reference binding to param_idents when we only use it to iterate over, especially now that it's owned.

Just moved the method name down to where the references are used a couple times so it's obvious why we're still taking a reference.

File: itest/rust/src/object_tests/object_test.rs [hunk 6]
```diff
@@ -948,6 +952,16 @@ pub mod object_test_gd {
...
         }
+
+        #[func]
+        fn return_self() -> Gd<Self> {
+            Gd::from_object(Self)
+        }
+
+        #[func]
+        fn return_nested_self() -> Array<Gd<<Self as GodotClass>::Base>> {
+            Array::from(&[<Self as GodotClass>::Base::new_gd()])
```
Comment (Bromeon) [inline itest/rust/src/object_tests/object_test.rs:963]: This could probably be:
```suggestion
            array![Self::return_self().upcast()]
```

File: itest/rust/src/object_tests/object_test.rs [hunk 7]
```diff
@@ -911,12 +911,16 @@ pub mod object_test_gd {
...
-    #[derive(GodotClass, Debug)]
-    #[class(init, base=RefCounted)]
-    struct ObjectTest;
+    mod nested {
+        use godot::prelude::*;
+        #[derive(GodotClass, Debug)]
+        #[class(init, base=RefCounted)]
+        pub(super) struct ObjectTest;
+    }
+    use nested::ObjectTest;
```
Comment (vortexofdoom) [inline itest/rust/src/object_tests/object_test.rs:920]: I nested the ObjectTest struct in its own little mod to make sure that nothing broke if I used a more qualified path in the impl block.

File: godot-macros/src/class/data_models/func.rs [hunk 8]
```diff
@@ -252,22 +257,49 @@ fn make_forwarding_closure(
...
+            tt => tt,
+        })
+        .collect()
+}
+
+pub(crate) fn into_signature_info(
+    class_name: &Ident,
+    signature: venial::Function,
+    has_gd_self: bool,
+) -> SignatureInfo {
```
Comment (Bromeon) [inline godot-macros/src/class/data_models/func.rs:286]: As mentioned before, I'd make `signature` the first parameter since it is now the "subject" of the "into" operation.

**Review by Bromeon — COMMENTED** [review]
Thanks, looks mostly good now!

File: godot-macros/src/class/data_models/func.rs [hunk 9]
```diff
@@ -252,22 +257,49 @@ fn make_forwarding_closure(
     }
 }
 
-pub(crate) fn get_signature_info(signature: &venial::Function, has_gd_self: bool) -> SignatureInfo {
+/// Maps each usage of `Self` to the struct it's referencing,
+/// since `Self` can't be used inside nested functions.
+fn map_self_to_class_name<T: FromIterator<TokenTree>>(
+    tokens: impl IntoIterator<Item = TokenTree>,
+    class_name: &Ident,
+) -> T {
```
Comment (Bromeon) [inline godot-macros/src/class/data_models/func.rs:265]: I would probably use a `where` close with two named type parameters `In` and `Out`, for symmetry reasons.

**Review by Bromeon — APPROVED** [review]
Thanks a lot!
