### PR TITLE
Fix `ThreadConfined<T>` using thread-unsafe `Drop`

### LINKED ISSUE #1281: ThreadConfined might be unsound on drop
As far as I can see, `ThreadConfined` is missing a `Drop` impl so rust will simply drop `value` without the thread check.

This violates the requirements of `DynamicSend` but I don't know the Godot side well enough to see if this is really an issue or not.

### PR DESCRIPTION
**Pull request by Bromeon**
Fixes #1281.

Also adds unit tests for `extract` + `drop`.

### CODE REVIEW

File: godot-core/src/task/futures.rs [hunk 1]
```diff
@@ -375,8 +376,10 @@ pub unsafe trait DynamicSend: Send + Sealed {
 }
 
 /// Value that can be sent across threads, but only accessed on its original thread.
+///
+/// When moved to another thread, the inner value can no longer be accessed and will be leaked when the `ThreadConfined` is dropped.
 pub struct ThreadConfined<T> {
-    value: T,
+    value: Option<T>,
```
Comment (TitanNano) [inline godot-core/src/task/futures.rs:382]: We could do this just with a `ManuallyDrop` that we never actually drop, but then we couldn't implement `Drop` for `ThreadConfined` to log the error.

**Comment by Bromeon** [comment]
Problem is that every failed `extract()` now causes a leak. So yes, it's sound, but it's no longer a casually usable check...

File: godot-core/src/task/futures.rs (hunk 1 above)
Comment (Bromeon) [reply godot-core/src/task/futures.rs:382]: I had `ManuallyDrop` first but it was messy to extract; the current one also needs no unsafe code. In this case it's probably not performance-critical.

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-1283

**Comment by Bromeon** [comment]
So, leaking is already problematic due to CI alone...
I do wonder if there's a way to "move back" the object in case of failed `extract` or so :thinking:

**Comment by Bromeon** [comment]
@TitanNano do you have a suggestion what we could do here? 

The [itests gated behind `#[cfg(feature = "experimental-threads")]`](https://github.com/godot-rust/gdext/blob/998341991a11fda1d157dd18f78b82302103ce65/itest/rust/src/engine_tests/async_test.rs#L131-L184) in `async_test.rs` currently cause memory leaks, so this might also happen in user projects.

Or does it only occur in combination with a panic indicating a bug that should anyway be fixed?

**Comment by TitanNano** [comment]
@Bromeon I've been thinking this over, and I don't see how we could do anything else here. Moving the value back to the origin thread seems impossible.

> Or does it only occur in combination with a panic indicating a bug that should anyway be fixed?

Yes, we always panic after the extraction fails, so the leak only occurs in combination with a panic.

To fix the test we might be able to use an `Object` instead of the `RefCounted` and free it after the test 🤔  

---

EDIT: only the `signal_future_non_send_arg_panic`  test should leak.

**Comment by Bromeon** [comment]
I implemented some hackery to move the `RefCounted` back to the old thread and drop it there. While we could use `Object`, that wouldn't test the leaking itself. Now we know that `RefCounted::drop()` isn't invoked, otherwise the double decrement would wreak havoc :monocle_face:
