### PR TITLE
Fix more UB in pointer calls, and leaks in general

### LINKED ISSUE #257: Using input method causes game to crash
I'm using an input method of the godot-api for a custom Npc class like so:

```rust
#[godot_api]
impl CharacterBody3DVirtual for Npc {
   ...
    fn input(&mut self, event: Gd<InputEvent>) {
   }
}
```
When i have gamepad connected to the pc (probably cause of joypad continuous input) and i run the game from the editor, the game randomly crashes after few seconds when triggering input via keyboard or mouse. Disconnecting the gamepad from pc solves the problem.

Trace log doesn't show any interesting stuff, these are few input records from terminal before crashing
```
Gd::drop   <godot_core::gen::classes::input::re_export::Input>
Gd::drop   <godot_core::gen::classes::input_event::re_export::InputEvent>
  Stat::dec   <godot_core::gen::classes::input_event::re_export::InputEvent>
  +-- was last=false
ptrcall: input
Gd::drop   <godot_core::gen::classes::input::re_export::Input>
Gd::drop   <godot_core::gen::classes::input_event::re_export::InputEvent>
  Stat::dec   <godot_core::gen::classes::input_event::re_export::InputEvent>
  +-- was last=false
  ```
  
  The crash itself looks like so:
  ```
  handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.dev1.official (db1302637023168f7becceb1c4ce13228e1b2a43)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f91fee42520] (??:0)
[2] /home/bonsai/GameDev/godot/godot4() [0x468ca27] (??:0)
[3] /home/bonsai/GameDev/godot/godot4() [0x45dbc1c] (??:0)
[4] /home/bonsai/GameDev/godot/godot4() [0x43a9493] (??:0)
[5] /home/bonsai/GameDev/godot/godot4() [0xe59641] (??:0)
[6] /home/bonsai/GameDev/godot/godot4() [0xe5df5a] (??:0)
[7] /home/bonsai/GameDev/godot/godot4() [0xde4090] (??:0)
[8] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f91fee29d90] (??:0)
[9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f91fee29e40] (??:0)
[10] /home/bonsai/GameDev/godot/godot4() [0xdf1f7e] (??:0)
-- END OF BACKTRACE --
  ```
  
 The problem **doesnt seem to happen when i**
 - disconnect gamepad from pc
 - not using mouse or keyboard while gamepad connected (i can press anything on the gamepad tho)
  
  @lilizoey suggested using ``std::mem::forget(event)`` at the end of the input method, which seems to solve the problem aswell. This little amnesia allows me to run the game without any issue. That led to the conclusion, that it might be **wrong handling of a reference count**
  
  Ive been also asked to reference the issue https://github.com/godot-rust/gdext/pull/204 as it might be related.

### LINKED ISSUE #267: `input_event` call fails while `CharacterBody3D` is moving
Node structure looks like this:

```rust
#[derive(GodotClass)]
#[class(init, base=CharacterBody3D)]
pub struct CharacterNode {
    #[base]
    base: Base<CharacterBody3D>,
}

#[godot_api]
impl CharacterBody3DVirtual for CharacterNode {
    fn input_event(
        &mut self,
        camera: Gd<Camera3D>,
        event: Gd<InputEvent>,
        position: Vector3,
        normal: Vector3,
        shape_idx: i64,
    ) { ... }
```

this intermittently throws the error (when the input_event is fired, e.g. when hovering over the body with the cursor):
```
thread '<unnamed>' panicked at 'Gd initialization failed; did you call share() on a dead instance?', /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:226:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:135:5
   3: core::panicking::panic_str
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:119:5
   4: core::option::expect_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:1879:5
   5: core::option::Option<T>::expect
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/option.rs:741:21
   6: godot_core::obj::gd::Gd<T>::from_opaque
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:225:27
   7: godot_core::obj::gd::Gd<T>::from_obj_sys_weak
             at /Users/jrockett/workspace/3rd-party/gdext/godot-ffi/src/godot_ffi.rs:196:13
   8: godot_core::obj::gd::Gd<T>::from_obj_sys
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:431:9
   9: <godot_core::obj::gd::Gd<T> as godot_ffi::godot_ffi::GodotFfi>::from_arg_ptr
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:557:13
  10: godot_ffi::godot_ffi::scalars::<impl godot_ffi::godot_ffi::GodotFuncMarshal for T>::try_from_arg
             at /Users/jrockett/workspace/3rd-party/gdext/godot-ffi/src/godot_ffi.rs:477:16
  11: <(R,P0,P1,P2,P3,P4) as godot_core::builtin::meta::signature::SignatureTuple>::ptrcall_mut
             at /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/builtin/meta/signature.rs:240:25
  12: <shared::combat::character::CharacterNode as godot_core::obj::traits::cap::ImplementsGodotVirtual>::__virtual_call::function
             at /Users/jrockett/workspace/isles_of_alcyon/shared/src/combat/character.rs:16:1
```

per [this](https://github.com/godot-rust/gdext/compare/master...lilizoey:gdextension:hotfix/type_name-in-gd-initialization-failure) change, we get a more descriptive error:
```
thread '<unnamed>' panicked at 'godot_core::obj::gd::Gd<godot_core::gen::classes::camera_3d::re_export::Camera3D> initialization failed; did you call share() on a dead instance?', /Users/jrockett/workspace/3rd-party/gdext/godot-core/src/obj/gd.rs:226:13
```

From my testing, this crashes consistently when the CharacterBody3D is moving (via `move_and_slide`). I have been unable to reproduce while the CharacterBody3D is stationary.

([relevant discord thread](https://discord.com/channels/723850269347283004/1043514894198255737/1105191823007305839))
OS: macOS Monterey 12.5, M1 2020
Godot Version: 4.0.1

### PR DESCRIPTION
**Pull request by lilizoey**
Fixes 3 issues, all done together because the test for the first one doesn't pass on latest godot without the other two fixes.

## UB in virtual method calls

Fixes UB caused by us dereferencing a pointer incorrectly. We initially assumed that in pointer calls, if an argument is an object then the pointer passed is either a `Ref<T>*` or a `T*`, but as it turns out it sometimes is `T**` instead. This happens whenever we're making a virtual call (which are always pointer calls) and `T` does not inherit from `RefCounted`.

Thus when we tried to dereference the pointer we'd be transmuting a `T*` into a `T`. Which is UB.

closes #267 

## Improper handling of refcount in virtual methods
We were previously not incrementing the refcount for objects we received in virtual methods. This is incorrect, it is our responsibility to increment the refcount. This seemed correct at the time because of the bug below.

## Unnecessary increment of recount on passing values to Godot
When passing a refcounted object to godot we would increment the refcount before passing it along. But godot would assume we did not do this, thus leading to a leak as godot would not decrement the refcount for us. 

This made it appear like godot incremented the refcount for us in the tests we had. However it was actually just that we had incremented the refcount and godot did not decrement it. 

closes #257

### CODE REVIEW

**Comment by GodotRust** [comment]
API docs are being generated and will be shortly available at: https://godot-rust.github.io/docs/gdext/pr-275

**Comment by lilizoey** [comment]
bors try

File: itest/rust/src/virtual_methods_test.rs [hunk 1]
```diff
@@ -463,3 +506,42 @@ fn test_notifications() {
...
+}
+
+#[godot_api]
+impl RigidBody2DVirtual for CollisionObject2DTest {
+    fn init(_: Base<RigidBody2D>) -> Self {
+        Self {
+            input_event_called: false,
+            viewport: None,
+        }
+    }
```
Comment (Bromeon) [inline itest/rust/src/virtual_methods_test.rs:525]: This could be compiler-generted via `#[class(init, base = RigidBody2D)]`.

File: godot-core/src/obj/as_arg.rs [hunk 2]
```diff
@@ -22,8 +22,11 @@ pub trait AsArg: Sealed {
 impl<T: GodotClass> Sealed for Gd<T> {}
 impl<T: GodotClass> AsArg for Gd<T> {
     fn as_arg_ptr(&self) -> sys::GDExtensionConstTypePtr {
-        // Pass argument to engine: increment refcount
-        <T::Mem as crate::obj::mem::Memory>::maybe_inc_ref(self);
+        // We're passing a reference to the object to the callee. If the reference count needs to be
+        // incremented then the callee will do so. We do not need to prematurely do so.
+        //
+        // In rust terms, if `T` is refcounted then we are effectively passing a `&Arc<T>`, and the callee
+        // would need to call `.clone()` if desired.
```
Comment (Bromeon) [inline godot-core/src/obj/as_arg.rs:29]: Great description, thanks! Should make sure we don't accidentally change this again 🙂 

Slight nitpick: uppercase "Rust" (maybe search for lowercase "rust", it happens in other places, too) 😉

File: godot-core/src/obj/gd.rs [hunk 3]
```diff
@@ -549,13 +549,19 @@ where
     // https://github.com/godotengine/godot-cpp/issues/954
 
     unsafe fn from_arg_ptr(ptr: sys::GDExtensionTypePtr, call_type: PtrcallType) -> Self {
-        if T::Mem::pass_as_ref(call_type) {
-            let obj_ptr = interface_fn!(ref_get_object)(ptr as sys::GDExtensionRefPtr);
-            // ref_get_object increments the ref_count for us
-            Self::from_obj_sys_weak(obj_ptr)
+        let obj_ptr = if T::Mem::pass_as_ref(call_type) {
+            // ptr is `Ref<T>*`
```
Comment (Bromeon) [inline godot-core/src/obj/gd.rs:553]: Maybe mention in a few words what `Ref<T>` is (for a reader not knowing Godot internals, it's not obvious).

It's also enough if you just add something like `(see GodotFfi for explanation)`, as it seems you already explain it elsewhere.

File: itest/godot/SpecialTests.gd [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+	assert_that(not collision_object.input_event_called())
+	assert_eq(collision_object.get_viewport(), null)
+
+	var event := InputEventMouseMotion.new()
+	event.global_position = Vector2.ZERO
+	window.push_unhandled_input(event)
+
+	# Ensure we run a full physics frame
+	await root.get_tree().physics_frame
+	await root.get_tree().physics_frame
```
Comment (Bromeon) [inline itest/godot/SpecialTests.gd:44]: This runs _two_ frames, no? If that's truly needed, could you add an explanation to that? At the moment the comments ("one full physics frame") seem to contradict the code.

**Review by Bromeon — COMMENTED** [review]
Thanks for the update!

There are now quite a few more types for the GDScript tests: `GDScriptExecutableTestCase`, `GDScriptHardcodedTestCase`, `GDScriptTestCase` (the abstract base), `TestSuiteSpecial`. I assume this is all due to the "skipping a physics frame", or any other reason?

Is it possible to inherit  `TestSuiteSpecial` from `TestSuite` for the sake of code reuse?

File: itest/godot/SpecialTests.gd (hunk 4 above)
Comment (lilizoey) [reply itest/godot/SpecialTests.gd:44]: from my understanding, it is like this: 
the first physics frame signal is emitted at the first physics frame, but at this point no physics has happened yet. the second physics frame signal is emitted at the second physics frame, at this point a full physics frame has been run.
i may be wrong though, but it didn't seem to consistently work with only one at least.

File: itest/rust/src/virtual_methods_test.rs (hunk 1 above)
Comment (lilizoey) [reply itest/rust/src/virtual_methods_test.rs:525]: yeah i mostly just wanted it to be clear exactly what they were initialized to. but since i actually check the values of these in the test it's probably not needed.

**Comment by lilizoey** [comment]
> Thanks for the update!
> 
> There are now quite a few more types for the GDScript tests: `GDScriptExecutableTestCase`, `GDScriptHardcodedTestCase`, `GDScriptTestCase` (the abstract base), `TestSuiteSpecial`. I assume this is all due to the "skipping a physics frame", or any other reason?

Yeah, it should also be usable if we have another test that we just cant run with our standard itest api. `GDScriptExecutableTestCase` is the same as the original `GDScriptTestCase` (as in it has the same code). It's just split into two now, the abstract base and the concrete class.  

> Is it possible to inherit `TestSuiteSpecial` from `TestSuite` for the sake of code reuse?

I'll try, probably, but i think i'd end up rewriting everything in `TestSuiteSpecial` anyway, since i need the asserts to write errors to a buffer with this implementation. Though maybe a bit more refactoring could avoid some of the code duplication.

**Comment by Bromeon** [comment]
Don't worry too much about that refactoring, can always be cleaned up later 🙂

**Comment by lilizoey** [comment]
> Don't worry too much about that refactoring, can always be cleaned up later slightly_smiling_face

turned out to be pretty simple

File: itest/godot/SpecialTests.gd (hunk 4 above)
Comment (lilizoey) [reply itest/godot/SpecialTests.gd]: i made the test runner wait for a physics frame instead of a process frame for initialization. that way i only need to wait for one physics frame here

**Comment by Bromeon** [comment]
bors try

**Comment by Bromeon** [comment]
@lilizoey it looks like this no longer passes memory checks with Godot upstream changes and/or #284 🤔 

See [failed CI job](https://github.com/godot-rust/gdext/actions/runs/5072511781/jobs/9110314796).

<details>
<summary>Undefined behavior</summary>

```
=================================================================
==2177==ERROR: AddressSanitizer: heap-use-after-free on address 0x61c0000076b8 at pc 0x5560a40a0327 bp 0x7ffc8d442c60 sp 0x7ffc8d442c50
READ of size 8 at 0x61c0000076b8 thread T0
    #0 0x5560a40a0326 in SelfList<GDScript>::self() const core/templates/self_list.h:135
    #1 0x5560a4046552 in GDScriptLanguage::finish() modules/gdscript/gdscript.cpp:2009
    #2 0x5560bcafc66a in ScriptServer::finish_languages() core/object/script_language.cpp:229
    #3 0x5560a24d3166 in Main::cleanup(bool) main/main.cpp:3538
    #4 0x5560a21fc3dd in main platform/linuxbsd/godot_linuxbsd.cpp:75
    #5 0x7f38a93f3082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
    #6 0x5560a21fbdad in _start (/home/runner/work/_temp/godot_bin/godot.linuxbsd.editor.dev.x86_64.san+0x3ab9ddad)

0x61c0000076b8 is located 1592 bytes inside of 1720-byte region [0x61c000007080,0x61c000007738)
freed by thread T0 here:
    #0 0x7f38aa1b340f in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x5560bb29a104 in Memory::free_static(void*, bool) core/os/memory.cpp:168
    #2 0x5560a2514cb1 in void memdelete<GDScript>(GDScript*) core/os/memory.h:112
    #3 0x5560a250b045 in Ref<GDScript>::unref() core/object/ref_counted.h:210
    #4 0x5560a24fbac6 in Ref<GDScript>::~Ref() core/object/ref_counted.h:222
    #5 0x5560a40343a3 in GDScript::~GDScript() modules/gdscript/gdscript.cpp:1449
    #6 0x5560a2514ca0 in void memdelete<GDScript>(GDScript*) core/os/memory.h:109
    #7 0x5560a250b045 in Ref<GDScript>::unref() core/object/ref_counted.h:210
    #8 0x5560a24fbac6 in Ref<GDScript>::~Ref() core/object/ref_counted.h:222
    #9 0x5560a4046eb0 in GDScriptLanguage::finish() modules/gdscript/gdscript.cpp:2009
    #10 0x5560bcafc66a in ScriptServer::finish_languages() core/object/script_language.cpp:229
    #11 0x5560a24d3166 in Main::cleanup(bool) main/main.cpp:3538
    #12 0x5560a21fc3dd in main platform/linuxbsd/godot_linuxbsd.cpp:75
    #13 0x7f38a93f3082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

previously allocated by thread T0 here:
    #0 0x7f38aa1b3808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5560bb2990a9 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x5560bb298fba in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x5560a40b5dfb in Ref<GDScript>::instantiate() core/object/ref_counted.h:216
    #4 0x5560a42800ed in GDScriptCache::get_shallow_script(String const&, Error&, String const&) modules/gdscript/gdscript_cache.cpp:254
    #5 0x5560a42ab0a8 in GDScriptCompiler::_gdtype_from_datatype(GDScriptParser::DataType const&, GDScript*) modules/gdscript/gdscript_compiler.cpp:127
    #6 0x5560a4326c0c in GDScriptCompiler::_populate_class_members(GDScript*, GDScriptParser::ClassNode const*, bool) modules/gdscript/gdscript_compiler.cpp:2434
    #7 0x5560a43362cd in GDScriptCompiler::compile(GDScriptParser const*, GDScript*, bool) modules/gdscript/gdscript_compiler.cpp:2832
    #8 0x5560a4016ea4 in GDScript::reload(bool) modules/gdscript/gdscript.cpp:783
    #9 0x5560a4281432 in GDScriptCache::get_full_script(String const&, Error&, String const&, bool) modules/gdscript/gdscript_cache.cpp:301
    #10 0x5560a4282065 in GDScriptCache::finish_compiling(String const&) modules/gdscript/gdscript_cache.cpp:333
    #11 0x5560a4336730 in GDScriptCompiler::compile(GDScriptParser const*, GDScript*, bool) modules/gdscript/gdscript_compiler.cpp:2847
    #12 0x5560a4016ea4 in GDScript::reload(bool) modules/gdscript/gdscript.cpp:783
    #13 0x5560a4281432 in GDScriptCache::get_full_script(String const&, Error&, String const&, bool) modules/gdscript/gdscript_cache.cpp:301
    #14 0x5560a405919e in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*, bool, float*, ResourceFormatLoader::CacheMode) modules/gdscript/gdscript.cpp:2598
    #15 0x5560bbab7541 in ResourceLoader::_load(String const&, String const&, String const&, ResourceFormatLoader::CacheMode, Error*, bool, float*) core/io/resource_loader.cpp:260
    #16 0x5560bbab8f71 in ResourceLoader::_thread_load_function(void*) core/io/resource_loader.cpp:311
    #17 0x5560bbabc516 in ResourceLoader::_load_start(String const&, String const&, ResourceLoader::LoadThreadMode, ResourceFormatLoader::CacheMode) core/io/resource_loader.cpp:487
    #18 0x5560b5b5c604 in ResourceLoaderText::load() scene/resources/resource_format_text.cpp:466
    #19 0x5560b5b9a8cf in ResourceFormatLoaderText::load(String const&, String const&, Error*, bool, float*, ResourceFormatLoader::CacheMode) scene/resources/resource_format_text.cpp:1640
    #20 0x5560bbab7541 in ResourceLoader::_load(String const&, String const&, String const&, ResourceFormatLoader::CacheMode, Error*, bool, float*) core/io/resource_loader.cpp:260
    #21 0x5560bbab8f71 in ResourceLoader::_thread_load_function(void*) core/io/resource_loader.cpp:311
    #22 0x5560bbabc516 in ResourceLoader::_load_start(String const&, String const&, ResourceLoader::LoadThreadMode, ResourceFormatLoader::CacheMode) core/io/resource_loader.cpp:487
    #23 0x5560bbabb4ef in ResourceLoader::load(String const&, String const&, ResourceFormatLoader::CacheMode, Error*) core/io/resource_loader.cpp:404
    #24 0x5560a24c4de1 in Main::start() main/main.cpp:3183
    #25 0x5560a21fc236 in main platform/linuxbsd/godot_linuxbsd.cpp:71
    #26 0x7f38a93f3082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

SUMMARY: AddressSanitizer: heap-use-after-free core/templates/self_list.h:135 in SelfList<GDScript>::self() const
Shadow bytes around the buggy address:
  0x0c387fff8e80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c387fff8e90: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c387fff8ea0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c387fff8eb0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c387fff8ec0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c387fff8ed0: fd fd fd fd fd fd fd[fd]fd fd fd fd fd fd fd fd
  0x0c387fff8ee0: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c387fff8ef0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c387fff8f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c387fff8f10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c387fff8f20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2177==ABORTING
```

</details>

**Comment by Bromeon** [comment]
bors try

**Review by Bromeon — APPROVED** [review]
