### PR TITLE
Fix methods always taking a mutable receiver

### LINKED ISSUE #206: Method calls always take a mutable reference to receiver
[Here](https://github.com/godot-rust/gdext/blob/c1c2d600dd5ab247a50a4ec7c35102df75ecc4f0/godot-core/src/macros.rs#L401) a virtual method call always tries to get a mutable reference to the receiver. [Here](https://github.com/godot-rust/gdext/blob/c1c2d600dd5ab247a50a4ec7c35102df75ecc4f0/godot-core/src/builtin/meta/signature.rs#L150) pointer calls do the same. And [here](https://github.com/godot-rust/gdext/blob/c1c2d600dd5ab247a50a4ec7c35102df75ecc4f0/godot-core/src/builtin/meta/signature.rs#L119) varcalls do.

### PR DESCRIPTION
**Pull request by lilizoey**
A lot of methods unnecessarily require a `&mut self` reference, but at least now methods actually request the kind of reference they're declared to take. 

closes #206

### CODE REVIEW

**Comment by lilizoey** [comment]
bors try

File: itest/rust/src/object_test.rs [hunk 1]
```diff
@@ -762,3 +763,65 @@ pub mod object_test_gd {
...
+fn double_use_reference() {
+    let double_use: Gd<DoubleUse> = Gd::new_default();
+    let emitter: Gd<SignalEmitter> = Gd::new_default();
+
+    emitter
+        .share()
+        .upcast::<Object>()
+        .connect("do_use".into(), double_use.callable("use_1"), 0);
+
+    let double_use_ref = double_use.bind();
```
Comment (Bromeon) [inline itest/rust/src/object_test.rs:809]: I'd name this `guard` and not `ref`.

File: itest/rust/src/object_test.rs [hunk 2]
```diff
@@ -762,3 +763,65 @@ pub mod object_test_gd {
...
+}
+
+#[godot_api]
+impl SignalEmitter {
+    #[signal]
+    fn do_use();
+}
+
+#[itest]
+fn double_use_reference() {
```
Comment (Bromeon) [inline itest/rust/src/object_test.rs:800]: Could you comment what this test is exactly testing?

File: itest/rust/src/object_test.rs [hunk 3]
```diff
@@ -762,3 +763,65 @@ pub mod object_test_gd {
...
+
+// ----------------------------------------------------------------------------------------------------------------------------------------------
+
+#[derive(GodotClass)]
+#[class(init, base=Object)]
+struct DoubleUse {
+    #[base]
+    base: Base<Object>,
+
+    used: atomic::AtomicBool,
```
Comment (Bromeon) [inline itest/rust/src/object_test.rs:775]: Can we not use `Cell<bool>` here?

We're not dealing with threads as far as I can see.

**Review by Bromeon — COMMENTED** [review]
Thank you!

I'm not sure about the `ptrcall_ref` naming. I know there's sometimes the distinction "_ref" vs "_mut" (e.g. `as_ref`, `as_mut`), but for operations it seems to be more like "" vs. "_mut" (e.g. `borrow` vs. `borrow_mut`, `iter` vs. `iter_mut`, our own `bind` vs. `bind_mut`). So `ptrcall` would be nicer 🙂

File: itest/rust/src/object_test.rs (hunk 3 above)
Comment (lilizoey) [reply itest/rust/src/object_test.rs:775]: i think so but I just find atomic bools easier  most of the time

**Comment by lilizoey** [comment]
> Thank you!
> 
> I'm not sure about the `ptrcall_ref` naming. I know there's sometimes the distinction "_ref" vs "_mut" (e.g. `as_ref`, `as_mut`), but for operations it seems to be more like "" vs. "_mut" (e.g. `borrow` vs. `borrow_mut`, `iter` vs. `iter_mut`, our own `bind` vs. `bind_mut`). So `ptrcall` would be nicer 🙂

that's fair, im probably taking over #210 after this which will require me to rework some of this code again so the names might change again. i might just add another set of functions for static calls tbh. but it'd be good if i could find a way to unify them a bit cause i don't super like all the code duplication.

File: itest/rust/src/object_test.rs (hunk 3 above)
Comment (Bromeon) [reply itest/rust/src/object_test.rs:775]: Apart from the fact that micro-optimizations don't matter in tests: atomics need synchronization (OS support) for thread safety. `std::cell::Cell` on the other hand is a direct wrapper around `UnsafeCell`, and since it's statically guaranteed to be single-threaded, it can optimize its read/writes [to (almost) pointer read/writes](https://doc.rust-lang.org/src/core/cell.rs.html#408-414).

Use the simplest tool for the job. Atomics are confusing in single-threaded contexts 🙂

**Comment by Bromeon** [comment]
Yeah, not too fond of the duplication either, but abstracting it may be even harder to understand. I agree it makes sense to revisit it during #210 though 👍

File: itest/rust/src/object_test.rs (hunk 3 above)
Comment (lilizoey) [reply itest/rust/src/object_test.rs:775]: i honestly find atomics less confusing but sure I'll change it

Comment (Bromeon) [reply itest/rust/src/object_test.rs:775]: > i honestly find atomics less confusing

With the whole `atomic::Ordering::{Release/Acquire}` ceremony? That's all complexity you don't have with `Cell`.

`Cell` is really just `set` + `get`, it cannot possibly get any simpler.

Comment (lilizoey) [reply itest/rust/src/object_test.rs:775]: if you just use acquire + release (or seqcst everywhere) then yeah it's easy. acquire means to load and release means to store.

it's when you start mixing in relaxed and such it gets confusing. but even then, in single threaded code im pretty sure relaxed is the same as seqcst. but i just use acquire and release/acqrel. in fact i believe Cell<bool> and AtomicBool with relaxed are semantically identical in single threaded code.

**Review by Bromeon — APPROVED** [review]
Thank you!

bors r+

**Comment by Bromeon** [comment]
Spurious error in the memcheck gcc, without any insights.
Might hint to UB elsewhere in gdext or Godot, but likely not related to this bugfix...

bors retry
