### PR TITLE
Fix `(no base)` showing up in all the docs

### LINKED ISSUE #159: `Variant` Parameter and Return Type Shows Up as `(no base)`
I have method with complex multiple dispatch of arguments and maybe empty return value. Since `Option<T>` is not supported as parameters nor return value, i use `Variant` as workaround.

Example:
```rust
#[func]
fn method(&self, arg0: Variant) -> Variant {
    // ...
}
```

But when i call it in GDScript, it errors with:
```
Line [XXX]: Cannot get return value of call to "method()" because it returns "void".
```

When i checked into it's documentation i saw this in methods section:
```
(no base) method(arg0: (no base))
```

Is this normal? I can't call it since it returns "void" even though it's not.

### PR DESCRIPTION
**Pull request by sayaks**
We were setting `class_name` to be `(no base)` in the `PropertyInfo` for all types by default. However that makes godot show the `class_name` in return values and arguments.

I dont know if there's a good way to test this? It would involve us checking what documentation is generated by godot which doesn't seem like something we can easily do.

closes #159

### CODE REVIEW

File: godot-core/src/builtin/meta/class_name.rs [hunk 1]
```diff
@@ -13,12 +13,17 @@ use crate::obj::GodotClass;
...
+#[derive(Default, Eq, PartialEq, Hash, Clone, Debug)]
 pub struct ClassName {
     backing: StringName,
 }
 
 impl ClassName {
+    /// In Godot, an empty `StringName` in a place that expects a class name, means that there is no class.
+    pub fn none() -> Self {
+        Self::default()
+    }
```
Comment (Bromeon) [inline godot-core/src/builtin/meta/class_name.rs:25]: Sorry, I meant "alternatively" as in "not providing default".

This avoids accidental implicit construction (we also don't need 2 methods doing the same thing here).

```suggestion
    /// In Godot, an empty `StringName` in a place that expects a class name, means that there is no class.
    pub fn none() -> Self {
        Self {
            backing: StringName::default(),
        }
    }
```

**Review by Bromeon — COMMENTED** [review]
True; I was actually looking for a method that would return something like a doc string, but couldn't find any. 

The method list was the 2nd best option, but you're right that it might just give us what we enter. This would still test that within gdext, we end up passing the right value for class names, but this is not really giving us anything at the current complexity.

**Review by Bromeon — APPROVED** [review]
Thanks a lot!

bors r+
